[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.27.1"
ci = "github"
unix-archive = ".zip"
windows-archive = ".zip"
installers = []
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]

[dist.github-custom-runners]
global = "ubuntu-22.04"
x86_64-unknown-linux-gnu = "ubuntu-22.04"
aarch64-unknown-linux-gnu = "ubuntu-22.04" 