id = "ziit"
name = "Ziit"
version = "1.0.0"
schema_version = 1
authors = ["PandaDEV <contact@pandadev.net>"]
description = "The Swiss army knife of code time tracking."
repository = "https://github.com/0pandadev/ziit-zed"

[language_servers.ziit]
name = "Ziit Language Server"
languages = [
  "ActionScript",
  "Ada",
  "Agda",
  "Aiken",
  "Angular",
  "Ansible",
  "Apache Avro (IDL)",
  "AsciiDoc",
  "ass",
  "Assembly",
  "Astro",
  "SpiceDB",
  "AWK",
  "Baml",
  "Beancount",
  "Bend",
  "Bicep",
  "Bicep Parameters",
  "GritQL",
  "bitbake",
  "Blade",
  "php_only",
  "Blueprint",
  "BQN",
  "Brainfuck",
  "C3",
  "Caddyfile",
  "Cadence",
  "Cairo",
  "Cap'n Proto",
  "Cedar",
  "CFEngine",
  "cfhtml",
  "cfml",
  "cfscript",
  "Circom",
  "Clarity",
  "Clojure",
  "COBOL",
  "comment",
  "CONL",
  "Cooklang",
  "Cpp2",
  "CQL",
  "Crystal",
  "ECR",
  "CSharp",
  "CSV",
  "Gherkin",
  "CUE",
  "Curry",
  "Cylc",
  "Cython",
  "D",
  "Dafny",
  "Dart",
  "DBML",
  "Desktop Entry",
  "devicetree",
  "Docker Compose",
  "Dockerfile",
  "DuckyScript",
  "Earthfile",
  "Edge",
  "EDI X12",
  "EJS",
  "Elisp",
  "Elixir",
  "HEEX",
  "Elm",
  "Handlebars",
  "Glimmer (JavaScript)",
  "Glimmer (TypeScript)",
  "env",
  "Erlang",
  "Exograph",
  "OpenFGA",
  "Firebase Rules",
  "Fish",
  "FlatBuffers",
  "Fortran",
  "Fountain",
  "FSharp",
  "G-code",
  "GDScript",
  "GDShader",
  "Godot Resource",
  "Gemini",
  "GitHub Actions",
  "Gleam",
  "Go Sum",
  "Go HTML Template",
  "Go Text Template",
  "GraphQL",
  "Gren",
  "GritQL",
  "GritQL Snippet",
  "Groovy",
  "GROQ",
  "Haml",
  "Hare",
  "Cabal",
  "Haskell",
  "Haxe",
  "HXML",
  "Helm",
  "HLSL",
  "HOCON",
  "HTML-Jinja",
  "Jinja-Inline",
  "http",
  "Hurl",
  "Hyprland Config",
  "Hyprlang",
  "iCal",
  "Inform 6",
  "ini",
  "Ink",
  "ion",
  "ion_schema",
  "ISLE",
  "Janet",
  "Jdl",
  "Jinja2",
  "jq",
  "JSON5",
  "JSON Lines",
  "Jsonnet",
  "JSP",
  "Julia",
  "Just",
  "KCL",
  "Kconfig",
  "Kdl",
  "Koto",
  "BibTeX",
  "LaTeX",
  "Lean 4",
  "Ledger",
  "RSTML",
  "LESS",
  "LilyPond",
  "LilyPond Scheme",
  "Liquid",
  "Logstash Config",
  "Lox",
  "Lua",
  "Luau",
  "Make",
  "MATLAB",
  "MDX",
  "MoonBit",
  "Motoko",
  "Move",
  "move",
  "Mustache",
  "Navi",
  "Navi Stream",
  "CMake",
  "Nickel",
  "Nim",
  "Nim Format String",
  "Noir",
  "Nu",
  "Nunjucks",
  "objectscript_udl",
  "Dune",
  "Menhir",
  "OCaml Interface",
  "OCaml",
  "OCamllex",
  "Reason Interface",
  "Reason",
  "Odin",
  "OMNeT++ MSG",
  "OMNeT++ NED",
  "OpenSCAD",
  "HCL",
  "OpenTofu Vars",
  "OpenTofu",
  "Org",
  "Pact",
  "Pascal",
  "Path of Exile Filter",
  "Perl",
  "Perm",
  "Pest",
  "PHP",
  "PHPDoc",
  "Pkl",
  "PlatformIO",
  "Animation.txt",
  "Pdxinfo",
  "PowerShell",
  "Prisma",
  "Prolog",
  "Pug",
  "Puppet",
  "PureScript",
  "Python constraints",
  "Python requirements",
  "QML",
  "Quadlet",
  "QuakeC",
  "R",
  "Racket",
  "RCL",
  "REDscript",
  "rego",
  "ReScript",
  "Rhai",
  "Risor",
  "Roc",
  "RON",
  "Roto",
  "RPM Spec",
  "RsHtml",
  "reST",
  "ERB",
  "HTML+ERB",
  "JS+ERB",
  "RBS",
  "Ruby",
  "YAML+ERB",
  "SageMath",
  "Scala",
  "Scheme",
  "SCSS",
  "Sieve",
  "Simula",
  "Slang",
  "Slim",
  "Smithy",
  "Standard ML",
  "Snakemake",
  "Solidity",
  "Sourcepawn",
  "SQL",
  "SSH Config",
  "Stan",
  "bazelrc",
  "Starlark",
  "Statamic Antlers",
  "Strace",
  "Surreal Query Language",
  "Svelte",
  "SystemRDL",
  "Tact",
  "TCL",
  "Templ",
  "Tera (CSS)",
  "Tera (HTML)",
  "Tera (JSON)",
  "Tera (TOML)",
  "Tera (YAML)",
  "Tera",
  "Terraform Vars",
  "Terraform",
  "Textproto",
  "Thrift",
  "tmux",
  "Todotxt",
  "TOML",
  "Fift",
  "Func",
  "TL-B",
  "Tolk",
  "TQL",
  "Tree-sitter Query",
  "Turtle",
  "Twig",
  "Txtar",
  "Typespec",
  "ucode",
  "Uiua",
  "Unison",
  "V",
  "Vala",
  "vCard",
  "Vento",
  "SystemVerilog",
  "VHDL",
  "VHS",
  "ViewTree ($mol)",
  "VRL",
  "Vue.js",
  "WebAssembly Text Format",
  "WDL",
  "WebIDL",
  "Wgsl",
  "WGSL/WESL",
  "whkd",
  "WIT",
  "Wren",
  "WeiXin Markup Language",
  "XDR Syntax Highlight",
  "XML",
  "YANG",
  "Yara",
  "Yarn Spinner",
  "Zig",
  "ziggy-schema",
  "ziggy",
  "Shell Script",
  "C",
  "C++",
  "CSS",
  "Diff",
  "Git Commit",
  "Go",
  "Go Mod",
  "Go Work",
  "JavaScript",
  "JSDoc",
  "JSON",
  "JSONC",
  "Markdown-Inline",
  "Markdown",
  "Python",
  "Regex",
  "Rust",
  "TSX",
  "TypeScript",
  "YAML",
  "Zed Keybind Context",
  "GLSL",
  "HTML",
  "Proto",
  "edge",
]
