name: Build

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Linux binary
        run: cargo build --release --package ziit-ls

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux
          path: target/release/ziit-ls
          retention-days: 5

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build macOS (Intel) binary
        run: cargo build --release --package ziit-ls

      - name: Upload macOS binary
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-darwin
          path: target/release/ziit-ls
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Windows binary
        run: cargo build --release --package ziit-ls

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-windows
          path: target/release/ziit-ls.exe
          retention-days: 5 