name: Build

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cargo-dist
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@0.28.0

      - name: Build for target
        run: cargo build --release --package ziit-ls --target ${{ matrix.target }}

      - name: Prepare artifacts (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/ziit-ls artifacts/
          
      - name: Prepare artifacts (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/ziit-ls.exe artifacts/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ziit-ls-${{ matrix.target }}
          path: artifacts
          retention-days: 5 