name: Build

permissions:
  contents: read

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cargo-dist
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-dist@0.28.0

      - name: Run cargo-dist
        run: |
          dist build --output-format=json --allow-dirty > dist-manifest.json
        env:
          CARGO_DIST_MANIFEST_PATH: ./dist-workspace.toml

      - name: Extract binaries
        run: |
          mkdir -p binaries
          
          # Find and extract each architecture's binary
          for target in aarch64-apple-darwin aarch64-unknown-linux-gnu x86_64-apple-darwin x86_64-unknown-linux-gnu x86_64-pc-windows-msvc; do
            echo "Processing $target"
            mkdir -p "binaries/$target"
            
            # Special handling for Windows
            if [[ "$target" == *windows* ]]; then
              find target/dist -path "*$target*" -name "*.exe" -exec cp {} "binaries/$target/" \;
            else
              # For Unix-like systems, find executable files
              find target/dist -path "*$target*" -type f -executable -exec cp {} "binaries/$target/" \;
            fi
          done

      - name: Upload aarch64-darwin
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-darwin
          path: binaries/aarch64-apple-darwin
          retention-days: 5
          
      - name: Upload aarch64-linux
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-linux
          path: binaries/aarch64-unknown-linux-gnu
          retention-days: 5
          
      - name: Upload x86_64-darwin
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-darwin
          path: binaries/x86_64-apple-darwin
          retention-days: 5
          
      - name: Upload x86_64-linux
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux
          path: binaries/x86_64-unknown-linux-gnu
          retention-days: 5
          
      - name: Upload x86_64-windows
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-windows
          path: binaries/x86_64-pc-windows-msvc
          retention-days: 5 